# Generated by Django 6.1 on 2026-08-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('year_level', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
